config/routes.rb
Rails.application.routes.draw do
  root :to => 'questions#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :questions, only: [:index]
  resources :users do
    resources :questions, except: [:index] do
      resources :responses do
        resources :best_responses, only: [:create, :destroy]
      end
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/best_response.rb
class BestResponse < ActiveRecord::Base
  belongs_to :response
  belongs_to :question

  validates_uniqueness_of :question_id
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :question, uniqueness: true, presence: true
  validates :description, uniqueness: true, presence: true

  has_many :responses
  belongs_to :user
  has_one :best_response

  def best_first
    self.responses.sort_by { |response| BestResponse.find_by(response_id: response.id)? 0 : 1 }
  end
end

app/models/response.rb
class Response < ActiveRecord::Base
  validates :response, uniqueness: true, presence: true

  belongs_to :user
  belongs_to :question
  has_many :votes

  def count
    Vote.where(response_id: self.id).count
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :name, uniqueness: true, presence: true

  has_many :questions
  has_many :responses
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :response
  validates_uniqueness_of :user_id, scope: :response_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
  def authorize
    if current_user.nil?
      flash[:alert] = "Not authorized"
      redirect_to login_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/best_responses_controller.rb
class BestResponsesController < ApplicationController
  def create
    @response = Response.find(params[:response_id])
    @old_response = @response.question.best_response.response
    @response.question.best_response.destroy
    best = BestResponse.create(response_id: @response.id, question_id: @response.question.id)
    respond_to do |format|
      format.html { redirect_to user_question_path(@response.question.user, @response.question) }
      format.js
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authorize, except: [:index, :show]

  def index
    @questions = Question.all
  end

  def new
    @user=User.find(params[:user_id])
    @question = @user.questions.new
  end

  def create
    @user = User.find(params[:user_id])
    @question = @user.questions.new(question_params)
    if @question.save
      flash[:notice] = "Question submitted!"
      redirect_to user_question_path(@user, @question)
    else
      render "new"
    end
  end

  def show
    @question = Question.find(params[:id])
    if current_user
      @response = current_user.responses.new
    else
      @response = Response.new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      flash[:notice] = "Question updated!"
      redirect_to user_question_path(@question.user, @question)
    else
      render 'edit'
    end
  end

private
  def question_params
    params.require(:question).permit(:question, :description)
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  before_filter :authorize

  def create
    @question = Question.find(params[:question_id])
    @response = Response.create!(response_params)
    respond_to do |format|
      format.html { redirect_to user_question_path(@question.user, @question) }
      format.js
    end
  end

  def edit
    @response = Response.find(params[:id])
    @question = @response.question
  end

  def update
    @response = Response.find(params[:id])
    if @response.update(response_params)
      respond_to do |format|
        format.html { redirect_to user_question_path(@response.question.user, @response.question) }
        format.js
      end
    end
  end

private
  def response_params
    params.require(:response).permit(:response).merge(user_id: current_user.id, question_id: params[:question_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = "Logged in!"
      redirect_to user_path(user)
    else
      flash.now.alert = "Name or password is invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Logged out!"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    session[:user_id] = nil
    redirect_to root_url
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/best_responses/create.js.erb
$('#chosen_link_<%= @response.id %>').hide();
$('.glyphicon').addClass("glyphicon glyphicon-star-empty");
$('#star_status_<%= @response.id %>').removeClass("glyphicon-star-empty").addClass("glyphicon glyphicon-star");
$('#response_<%= @response.id %>').prependTo("#all_responses");

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stackoverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "Stack Overflow", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "Questions", questions_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <% if current_user %>
            <li><%= link_to "New Question", new_user_question_path(current_user) %></li>
          <% end %>
        </ul>
        <% if current_user %>
          <%= link_to "Logout", session_path("current"), method: "delete", class: "pull-right" %>
          <span class="pull-right">Logged in as <%= current_user.name %>.</span>
        <% else %>
          <%= link_to "Sign up", signup_path, class: "pull-right" %>
          <%= link_to "Login", new_session_path, class: "pull-right" %>
        <% end %>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </div>
</body>
</html>

app/views/questions/_form.html.erb
<%= render("layouts/errors", :object => @question) %>

<%= form_for [@question.user, @question] do |f| %>
  <div class="form-group">
    <%= f.label :question %>
    <%= f.text_field :question %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/questions/_question.html.erb
<tr>
  <td><%= link_to question.question, user_question_path(question.user, question) %></td>
  <td><%= question.created_at %></td>
  <td><%= link_to question.user.name, user_path(question.user) %></td>
  <td><%= question.responses.count %></td>
</tr>

app/views/questions/edit.html.erb
<div class="page-header">
  <h1>Edit question</h1>
</div>

<%= render 'form' %>

app/views/questions/index.html.erb
<div class="row">
  <div class="col-md-8">
    <h4>Questions</h4>
    <table class="table table-striped">
      <thead>
      <tr>
        <th>Question</th>
        <th>Date Posted</th>
        <th>User</th>
        <th>Responses</th>
      </tr>
      <tbody>
        <%= render @questions %>
      </tbody>
    </table>
  </div>
  <div class="col-md-4">
    <h4>Hot Questions</h4>
  </div>
</div>

app/views/questions/new.html.erb
<div class="page-header">
  <h1>Post a new question</h1>
</div>

<%= render 'form' %>

app/views/questions/show.html.erb
<div class="page-header">
  <h1><%= @question.question %></h1>
  <p>Posted by <%= link_to @question.user.name, user_path(@question.user) %>
   on <%= @question.created_at %>
   <% if current_user == @question.user %>
      <%= link_to "Edit", edit_user_question_path(@question.user, @question) %></p><% end %>
</div>

<h4><%= @question.description %></h4>

<h3>Responses</h3>
<hr>
<div id ="all_responses">
  <%= render @question.best_first %>
</div>
<% if current_user %>
  <%= render 'responses/form' %>
<% end %>

app/views/responses/_form.html.erb
<%= render("layouts/errors", :object => @response) %>

<%= form_for [@question.user, @question, @response], remote: true do |f| %>
  <div class="form-group">
    <%= f.label :response %>
    <%= f.text_area :response %>
  </div>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/responses/_response.html.erb
<div class="panel panel-default" id="response_<%= response.id %>">
  <div class="panel-heading">
    <h3 class="panel-title">
      <%= link_to response.user.name, user_path(response.user) %>
      <% if current_user == response.user %>
        <span class='pull-right'><%= link_to "Edit", edit_user_question_response_path(response.question.user,response.question,response), id: "edit_link_#{response.id}", remote: true %></span>
      <% elsif current_user == response.question.user && response.question.best_response.response != response %>
        <span class='pull-right'><%= link_to "Mark best", user_question_response_best_responses_path(response.question.user,response.question,response), method: :post, id: "chosen_link_#{response.id}", remote: true %></span>
      <% end %>
      <span class='pull-right'><%= response.created_at %></span>
      <% if response.question.best_response && response.question.best_response.response == response %>
        <span id="star_status_<%= response.id %>" class='pull-right glyphicon glyphicon-star'></span>
      <% else %>
        <span id="star_status_<%= response.id %>" class='pull-right glyphicon glyphicon-star-empty'></span>
      <% end %>
    </h3>
  </div>
  <div class="panel-body">
   <p><span id="response_text_<%= response.id %>"><%= response.response %></span></p>
  </div>
</div>

app/views/responses/create.js.erb
$('#all_responses').append('<%= j render(@response) %>');

app/views/responses/edit.js.erb
$('#edit_link_<%= @response.id %>').hide().after('<%= j render("form") %>');

app/views/responses/update.js.erb
$('#edit_link_<%= @response.id %>').show()
$('#edit_response_<%= @response.id %>').remove()
$('#response_text_<%= @response.id %>').text("<%= @response.response %>")

app/views/users/index.html.erb
<div class="jumbotron">
  <h1>All Users</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Questions Posted</th>
      <th>Responses Posted</th>
    </tr>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.name, user_path(user) %></td>
        <td><%= user.questions.count %></td>
        <td><%= user.responses.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="page-header">
  <h1>Sign up! <small>Stack Overflow</small></h1>
</div>

<%= form_for @user do |f| %>
  <%= render("layouts/errors", :object => @user) %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Sign Up", class: "btn btn-primary" %>
<% end %>

app/views/users/show.html.erb
<div class="page-header">
  <h1><%= @user.name %></h1>
</div>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Question</th>
    <th>Date Posted</th>
    <th>User</th>
    <th>Responses</th>
  </tr>
  <tbody>
    <%= render @user.questions %>
  </tbody>
</table>

<% if current_user %>
  <p><%= link_to "Delete Account", user_path, data: {method: "delete"}, class: "btn btn-danger" %></p>
<% end %>